//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NL.GI.ComponentesWPF.Cliente.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NL.GI.ComponentesWPF.Cliente.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acessos.
        /// </summary>
        public static string Acessos {
            get {
                return ResourceManager.GetString("Acessos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerta.
        /// </summary>
        public static string Alerta {
            get {
                return ResourceManager.GetString("Alerta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualizar.
        /// </summary>
        public static string Atualizar {
            get {
                return ResourceManager.GetString("Atualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localizar.
        /// </summary>
        public static string Buscar {
            get {
                return ResourceManager.GetString("Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capitalizado.
        /// </summary>
        public static string Capitalizado {
            get {
                return ResourceManager.GetString("Capitalizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string Editar {
            get {
                return ResourceManager.GetString("Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir.
        /// </summary>
        public static string Excluir {
            get {
                return ResourceManager.GetString("Excluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportar.
        /// </summary>
        public static string Exportar {
            get {
                return ResourceManager.GetString("Exportar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportar arquivos em: .
        /// </summary>
        public static string ExportarMensagem {
            get {
                return ResourceManager.GetString("ExportarMensagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportar PDF.
        /// </summary>
        public static string ExportarPDF {
            get {
                return ResourceManager.GetString("ExportarPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimir.
        /// </summary>
        public static string Imprimir {
            get {
                return ResourceManager.GetString("Imprimir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo.
        /// </summary>
        public static string Incluir {
            get {
                return ResourceManager.GetString("Incluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maiúsculo.
        /// </summary>
        public static string Maiusculo {
            get {
                return ResourceManager.GetString("Maiusculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minúsculo.
        /// </summary>
        public static string Minusculo {
            get {
                return ResourceManager.GetString("Minusculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mudar senha.
        /// </summary>
        public static string MudarSenha {
            get {
                return ResourceManager.GetString("MudarSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outros.
        /// </summary>
        public static string Outros {
            get {
                return ResourceManager.GetString("Outros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        public static string Salvar {
            get {
                return ResourceManager.GetString("Salvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não há mais resultados..
        /// </summary>
        public static string SemMaisResultados {
            get {
                return ResourceManager.GetString("SemMaisResultados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não há resultados..
        /// </summary>
        public static string SemResultados {
            get {
                return ResourceManager.GetString("SemResultados", resourceCulture);
            }
        }
    }
}
